project:
  type: website
  output-dir: docs

website:
  title: "Macroeconometrics Students Present"
  navbar:
    background: "light"
    right:
    - icon: github
      href: https://github.com/donotdespair/Bayesian-Autoregressions

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



